<?php

namespace Database\Seeders;

use App\Models\ModuleInputField;
use App\Models\SystemRole;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ModuleInputFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        ModuleInputField::truncate();
        ModuleInputField::insert([
            ['field_name' => 'company_email', 'field_ids' => 'company_email', 'columns_name' => 'company_email', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 1, 'percentage' => 5, 'display_name' => 'Company Email', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'company_phone', 'field_ids' => 'company_phone', 'columns_name' => 'company_phone', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 2, 'percentage' => 5, 'display_name' => 'Company phone number', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'company_logo_label', 'field_ids' => 'company_logo_label', 'columns_name' => 'logo', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 3, 'percentage' => 5, 'display_name' => 'Logo', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'alternative_email', 'field_ids' => 'alternate_email', 'columns_name' => 'alternative_email', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 4, 'percentage' => 5, 'display_name' => 'Alternative Email', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'alternative_phone', 'field_ids' => 'alternative_phone', 'columns_name' => 'alternative_phone', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 5, 'percentage' => 5, 'display_name' => 'Alternative Phone', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'registration_nib', 'field_ids' => 'registration_nib', 'columns_name' => 'registrantion_NIB', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 6, 'percentage' => 5, 'display_name' => 'NIB', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'nib_file_image_div', 'field_ids' => 'nib_file_image_div', 'columns_name' => 'nib_file', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 7, 'percentage' => 5, 'display_name' => 'NIB File', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'npwp', 'field_ids' => 'npwp', 'columns_name' => 'npwp', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 8, 'percentage' => 5, 'display_name' => 'NPWP', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'npwp_file_image_div', 'field_ids' => 'npwp_file_image_div', 'columns_name' => 'npwp_file', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 9, 'percentage' => 5, 'display_name' => 'NPWP File', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'website', 'field_ids' => 'website', 'columns_name' => 'web_site', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 10, 'percentage' => 5, 'display_name' => 'Website', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'establish_in', 'field_ids' => 'establish_in', 'columns_name' => 'establish_in', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 11, 'percentage' => 5, 'display_name' => 'Company Establishment Date', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'owner_full_name', 'field_ids' => 'owner_full_name', 'columns_name' => 'owner_full_name', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 12, 'percentage' => 5, 'display_name' => 'Owner full name', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'address', 'field_ids' => 'address', 'columns_name' => 'address', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 13, 'percentage' => 5, 'display_name' => 'Address', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'commercial_tc_image_div', 'field_ids' => 'commercial_tc_image_div', 'columns_name' => 'termsconditions_file', 'table_name' => 'companies', 'getby_columnname' => 'id', 'priority' => 14, 'percentage' => 2, 'display_name' => 'Commercial T&C', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'number_of_employee', 'field_ids' => 'number_of_employee', 'columns_name' => 'number_of_employee', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 15, 'percentage' => 5, 'display_name' => 'Number Of Employees', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'average_sales', 'field_ids' => 'average_sales', 'columns_name' => 'average_sales', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 16, 'percentage' => 2, 'display_name' => 'Average Sales', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'annual_sales', 'field_ids' => 'annual_sales', 'columns_name' => 'annual_sales', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 17, 'percentage' => 2, 'display_name' => 'Annual Sales', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'financial_target', 'field_ids' => 'financial_target', 'columns_name' => 'financial_target', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 18, 'percentage' => 2, 'display_name' => 'Financial Target', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'type', 'field_ids' => 'type', 'columns_name' => 'type', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 19, 'percentage' => 2, 'display_name' => 'Business Type', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'category', 'field_ids' => 'category', 'columns_name' => 'category', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 20, 'percentage' => 3, 'display_name' => 'Category', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'description', 'field_ids' => 'description', 'columns_name' => 'description', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 21, 'percentage' => 3, 'display_name' => 'Description', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'license_image_div', 'field_ids' => 'license_image_div', 'columns_name' => 'license_image', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 22, 'percentage' => 2, 'display_name' => 'License image', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'bank_statement_image_div', 'field_ids' => 'bank_statement_image_div', 'columns_name' => 'bank_statement_image', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 23, 'percentage' => 2, 'display_name' => 'Bank Statement Image', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'annual_financial_statement_image_div', 'field_ids' => 'annual_financial_statement_image_div', 'columns_name' => 'annual_financial_statement_image', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 24, 'percentage' => 3, 'display_name' => 'Annual Financial Statement', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'ownership_percentage', 'field_ids' => 'ownership_percentage', 'columns_name' => 'ownership_percentage', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 25, 'percentage' => 2, 'display_name' => 'Ownership (%)', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'siup_number', 'field_ids' => 'siup_number', 'columns_name' => 'siup_number', 'table_name' => 'company_other_information', 'getby_columnname' => 'company_id', 'priority' => 26, 'percentage' => 2, 'display_name' => 'Siup number', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['field_name' => 'ProductCategory[]', 'field_ids' => 'product_cat_id0', 'columns_name' => 'product_cat_id', 'table_name' => 'company_consumptions', 'getby_columnname' => 'user_id', 'priority' => 27, 'percentage' => 3, 'display_name' => 'null', 'module_name' => 'Company Information', 'system_role_id' => SystemRole::FRONTOFFICE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
