<?php

return array (
  'content' => '<div class="row justify-content-center">
                <div class="col-md-12 my-4">
                    <h1 class="text-center color-primary">Syarat dan Ketentuan</h1>
                </div>
                <div class="col-md-10 text-justify">
                    <h6 class="lh-base">DOKUMEN INI ADALAH DOKUMEN ELEKTRONIK YANG DIDASARKAN PADA UNDANG-UNDANG NOMOR 7 TAHUN 2014 TENTANG PERDAGANGAN DAN PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 80 TAHUN 2019 TENTANG PERDAGANGAN MELALUI SISTEM ELEKTRONIK BESERTA TURUNANNYA. DOKUMEN ELEKTRONIK INI DIINTEGRASIKAN OLEH SISTEM KOMPUTER DAN TIDAK MEMBUTUHKAN DOKUMEN FISIK MAUPUN TANDA TANGAN DIGITAL. MOHON BACA DENGAN TELITI SYARAT DAN KETENTUAN YANG BERLAKU. JIKA ANDA TIDAK SETUJU DENGAN SYARAT DAN KETENTUAN YANG BERLAKU DI DALAM DOKUMEN INI, KLIK TANDA KELUAR DAN ANDA DILARANG MENGGUNAKAN PLATFORM INI DENGAN TUJUAN APAPUN.
                    </h6>

                    <ol class="list-group">
                        <li class="ms-4 my-3">
                            <h5 class=" my-3">KETENTUAN UMUM</h5>
                            <p>Nama domain website yang akan digunakan adalah “www.blitznet.co.id” (selanjutnya disebut sebagai <strong>“Platform”</strong>), yang dimiliki oleh PT Blitznet Upaya Indonesia, sebuah perusahaan di Negara Kesatuan Republik Indonesia yang tunduk pada perundang-undangan di Negara Kesatuan Republik Indonesia, beralamat di Alamanda Tower lantai 25 Jl. TB Simatupang Kav. 23-24, Cilandak Barat, Cilandak, Jakarta Selatan, DKI Jakarta (Selanjutnya akan disebut sebagai <strong>“blitznet”</strong>). Pengguna Platform ini adalah Pembeli dan Pemasok yang menggunakan layanan blitznet sebagai Platform transaksi jual dan beli (selanjutnya akan disebut sebagai <strong>“Pengguna”</strong>)</p>
                            <p>Istilah-istilah yang akan digunakan di dalam dokumen syarat dan ketentuan (selanjutnya akan disebut sebagai <strong>“Perjanjian”</strong>) ini, digunakan sebagai dasar penggunaan Platform ini bagi Pengguna, dan sebagai dasar blitznet untuk menyediakan layanan Platform ini kepada Pengguna (selanjutnya akan disebut sebagai <strong>“Layanan”</strong>). Perjanjian ini berlaku mengikat untuk Pengguna, para pengguna lain di Platform blitznet, dan blitznet. Pengguna diwajibkan untuk membaca dan menyetujui Perjanjian ini dan Kebijakan Perusahaan milik blitznet  sebelum Pengguna dapat menggunakan layanan blitznet melalui Platform ini. Dengan mengunjungi/mengakses/mengunduh/atau menggunakan Platform ini, blitznet meyakini bahwa anda telah sepenuhnya membaca, memahami dan menyetujui syarat dan ketentuan yang berlaku. Sebagai bukti persetujuan, Pengguna dapat meng-klik “Setuju” di Platform ini, yang kemudian menjadi pengganti tanda tangan Pengguna. Pengguna diwajibkan memahami dan cermat dalam membaca Perjanjian ini. Perjanjian dapat diubah sewaktu-waktu oleh blitznet dan tidak mengubah persetujuan Pengguna terhadap Perjanjian ini. 
                            </p>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">RUANG LINGKUP LAYANAN BLITZNET</h5>
                            <ul class="list-group ms-5 my-3">
                                <li>Melalui Platform, blitznet menyediakan layanan blitznet yang berupa, namun tidak terbatas pada, (i) menyediakan ruang virtual yang disediakan oleh pihak ketiga dan digunakan oleh para Pengguna untuk melakukan negosiasi atau berinteraksi dengan sesama Pengguna dan meningkatkan keuntungan dan efisiensi perdagangan; (ii) mengumpulkan informasi Pengguna; (iii) data pendukung lainnya termasuk data, laporan, teks, gambar, suara, video dan konten-konten yang berasal dari data-data yang sudah disebutkan sebelumnya tanpa melanggar ketentuan di dalam UU ITE, UU lain yang mengaturnya serta Peraturan turunannya (selanjutnya disebut <strong>“konten”</strong>), dan (iv) layanan khusus atau layanan tambahan yang akan diberikan oleh blitznet dari waktu ke waktu.</li>
                                <li class="mt-2">blitznet hanya menyediakan ruang virtual. blitznet tidak membuat/memproduksi/mendesain produk dan/atau layanan yang dibeli oleh Pengguna melalui Platform atau juga tidak memberikan jaminan dan representasi apa pun tentang keaslian dan kualitas produk/layanan. Semua transaksi menjadi tanggung jawab Pengguna. Perjanjian ini tidak akan dianggap menciptakan kemitraan, usaha patungan, atau hubungan bisnis bersama lainnya antara blitznet dan pihak lain.</li>
                                <li class="mt-2">Dalam hal mengakses platform blitznet melalui telepon seluler, Pengguna akan dibebankan pada biaya internet yang sudah distandarisasi oleh masing-masing penyedia layanan internet. Dengan menggunakan layanan blitznet, Pengguna setuju bahwa blitznet akan berkomunikasi dengan Pengguna melalui Platform dan cara lain seperti SMS, pesan multimedia, surat elektronik, chat, atau bentuk-bentuk lainnya seperti namun tidak terbatas pada push notification, reminders, alerts dan fitur-fitur lainnya yang berhubungan dengan pemberitahuan layanan blitznet dan informasi lainnya. blitznet tidak bertanggung jawab terhadap email, SMS, atau pesan lainnya yang berisikan promosi dan dikirimkan kepada Pengguna dan tidak mengatas namakan blitznet.</li>

                            </ul>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">AKSES PLATFORM, LISENSI DAN KETENTUAN LAINNYA</h5>
                            <ul class="list-group ms-5 my-3">
                                <li>Berdasarkan syarat dan ketentuan yang disebutkan di dalam Perjanjian ini, Pengguna dapat mengakses dan menggunakan Platform dan perangkat lunak yang akan dibuat oleh blitznet untuk menghubungan Layanan blitznet dengan aplikasi seluler (di masa yang akan datang maupun di masa sekarang) (selanjutnya disebut sebagai “Platform”) yang akan memuat data informasi rahasia dan hak milik yang dilindungi oleh Hak Cipta dan hukum yang berkaitan dengannya. Pengguna dengan ini mengakui dan menyetujui bahwa blitznet, atas kebijakannya, setiap saat selama penggunaan Platform tidak dapat menyediakan bagian apa pun dari Layanan blitznet. Seluruh hak, nama baik, dan keuntungan yang ada di dalam dan bagi Platform serta komponen lainnya akan secara eksklusif dimiliki oleh blitznet. Pengguna diwajibkan mematuhi seluruh pemberitahuan, code of conduct serta kebijakan yang diterbitkan oleh blitznet untuk meningkatkan kewaspadaan Pengguna terhadap adanya kemungkinan kebocoran data yang anda masukan di dalam Platform ini.</li>
                                <li class=" mt-2">blitznet berhak terhadap penghentian maupun perubahan baik seluruh maupun sebagian Perjanjian ini sepanjang dipandang perlu tanpa memberikan terlebih dahulu pemberitahuan kepada Pengguna. Perubahan dapat berupa namun tidak terbatas pada hak-hak yang berkaitan dengan pemungutan biaya layanan. blitznet menyarankan Pengguna untuk membaca kembali pemberitahuan-pemberitahuan penting mengenai perubahan syarat dan ketentuan yang berlaku di Platform. Jika setelah adanya perubahan mengenai syarat dan ketentuan yang berlaku di Platform telah dikirimkan, dan Pengguna tetap menggunakan Platform, maka Pengguna dianggap memahami dan menyetujui perubahan yang dilakukan oleh blitznet. Seluruh perubahan berlaku segera setelah pemberitahuan tentang perubahan dikirimkan. Perjanjian ini akan diubah atau diaddendum secara berkala, dan bersifat mengikat bagi para pihak, dalam hal ini, Pengguna. jika Pengguna mengunjungi, menggunakan atau memanfaatkan layanan blitznet melalui Platform, Pengguna dianggap telah menyetujui seluruh syarat dan ketentuan yang berlaku.</li>
                                <li class=" mt-2">Platform ini dapat diakses secara bebas oleh Pengguna namun; pengguna diharuskan melakukan registrasi ke website www.blitznet.co.id dan membuat akun untuk dapat mengakses seluruh layanan yang disediakan oleh blitznet. jika Pengguna melakukan registrasi atas nama perusahaan, maka Pengguna akan mewakili perusahaan dan diwajibkan untuk: (a) memasukan seluruh legalitas perusahaan; (b) menggunakan alamat kantor pusat perusahaan sebagai data yang dimasukan ke dalam Platform; (c) seluruh informasi yang dimasukan ke dalam platform selama proses registrasi harus diisi dengan benar dan lengkap sesuai dengan legalitas perusahaan terbaru yang berlaku; (d) Pengguna membebaskan blitznet terhadap tanggung jawab pemalsuan identitas yang dilakukan oleh Pengguna; (e) blitznet dan Pengguna akan bertanggung jawab pada kewajiban pajak masing-masing. Pengguna akan membebaskan blitznet dari kewajiban terhadap pajak yang bukan merupakan kewajiban blitznet sepanjang transaksi yang terjadi di platform.<br>
                                    Kantor cabang atau kantor perwakilan tidak diperbolehkan memisahkan akunnya di dalam Platform ini, seluruh kantor cabang dan kantor perwakilan akan ada di bawah kantor pusat yang didaftarkan ke Platform. 
                                    <br>
                                    Layanan yang disediakan oleh blitznet hanya akan bisa berlaku bagi seluruh warga negara Indonesia yang sudah cakap hukum, maka, Pengguna harus merupakan warga negara Indonesia yang sudah cakap hukum atau berusia di atas 21 tahun. blitznet meminta Pengguna untuk mematuhi persyaratan ini. Jika blitznet mengetahui adanya pelanggaran, maka blitznet berhak untuk memutus seluruh pelayanan kepada Pelanggan yang melanggar. 

                                </li>
                                <li class=" mt-2">Perjanjian ini berlaku untuk seluruh Pengguna, termasuk para Pengguna tamu, pengguna terdaftar sebagai Pengguna gratis maupun terdaftar sebagai Pengguna berbayar yang mengakses Platform dan me memanfaatkan layanan blitznet secara online (termasuk di dalamnya melalui aplikasi seluler) tujuan apapun sesuai dengan Perjanjian ini bersama dengan syarat dan ketentuan tambahan apa pun yang mungkin berlaku untuk layanan tertentu yang digunakan/diakses oleh Pengguna. Jika terjadi konflik atau inkonsistensi antara ketentuan apa pun dari syarat dan ketentuan yang disebutkan di sini dengan layanan tertentu, ketentuan syarat dan ketentuan yang berlaku untuk layanan khusus tersebut akan berlaku.
                                </li>
                            </ul>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">KETENTUAN PENGGUNAAN JASA LOGISTIK</h5>
                            <p>Dalam hal penggunaan jasa logistik oleh Pengguna kepada armada yang bekerja sama dengan blitznet, Pengguna harus memerhatikan ketentuan-ketentuan berikut: (a) Pengguna harus terlebih dahulu menyebutkan berat barang yang akan dikirimkan secara jelas di dalam dokumen Request for Quotation (RFQ); (b) Pengguna wajib memberikan tanggapan dan jawaban terhadap Quotation (Penawaran) yang diberikan oleh jasa logistik yang dipilih oleh Pengguna; (c) Dalam hal Pengguna tidak memberikan tanggapan dan jawaban terhadap Quotation (Penawaran) yang diberikan oleh jasa logistik terpilih, maka Pengguna dianggap setuju terhadap Quotation (Penawaran) tersebut; (d) Dalam hal adanya perbedaan berat di antara dokumen RFQ dan Penawaran, dan tidak ada tanggapan dari Pengguna mengenai perbedaan tersebut, maka dokumen Penawaran dianggap benar dan selisih pembayaran dibebankan kepada Pengguna.</p>
                        </li>
                        <li class="ms-4 my-3">
                            <h5 class=" my-3">HAK KEKAYAAN INTELEKTUAL</h5>
                            <p>blitznet adalah pemilik sah dan berhak terhadap seluruh aset milik blitznet yang ada di bawah peraturan perundangan Indonesia. Hak kekayaan intelektual milik blitznet termasuk namun tidak terbatas pada desain, tampilan, teks, gambar, grafik, suara, video dan lainnya. Konten blitznet yang mencakup rahasia dagang  dan hak kekayaan intelektual dilindungi oleh Undang-Undang Nomor 28 Tahun 2014 tentang Hak Cipta dan peraturan lain di bawahnya. Semua hak milik, kepemilikan, dan hak kekayaan intelektual yang digunakan dalam Layanan blitznet dan kontennya akan tetap berada pada blitznet, afiliasinya setiap saat, atau milik pemberi lisensi konten blitznet, sesuai dengan keadaannya.
                            </p>
                            <p>Semua hak yang tidak diklaim berdasarkan perjanjian ini atau oleh blitznet, dengan ini dilindungi undang-undang. Informasi yang diberikan dalam Layanan blitznet dimaksudkan, semata-mata untuk memberikan informasi umum untuk penggunaan pribadi Pengguna, yang menerima tanggung jawab penuh atas penggunaannya. blitznet tidak mewakili atau mendukung keakuratan atau keandalan informasi apa pun, atau iklan (selanjutnya disebut, "konten") yang terdapat pada, didistribusikan melalui, atau ditautkan, diunduh, atau diakses dari situs web blitznet atau lainnya (termasuk melalui aplikasi seluler), atau kualitas dari setiap produk, informasi atau materi lain yang ditampilkan, atau diperoleh oleh Pengguna sebagai hasil dari iklan atau informasi atau penawaran lain dalam atau sehubungan dengan layanan.</p>
                            <p>blitznet tidak bertanggung jawab atas kesalahan atau kelalaian apa pun, atau atas hasil yang diperoleh dari penggunaan informasi apa pun. Semua informasi dalam Layanan blitznet diberikan "sebagaimana adanya" tanpa jaminan kelengkapan, keakuratan, ketepatan waktu atau hasil yang diperoleh dari penggunaan informasi ini, dan tanpa jaminan dalam bentuk apapun, tersurat maupun tersirat, termasuk, namun tidak terbatas pada, jaminan kinerja, dapat diperjualbelikan, dan kesesuaian untuk tujuan tertentu. Tidak ada satu data pun yang dimasukan ke dalam Platform yang dapat menggantikan penyelidikan independen dan penilaian teknis dan bisnis yang baik dari pengguna. Dalam keadaan apapun blitznet tidak bertanggung jawab atas segala kerusakan langsung, tidak langsung, insidental, hukuman, atau mengandung konsekuensi dalam bentuk apapun sehubungan dengan layanan, materi, dan produk. Pengguna layanan blitznet ini dengan ini harus mengakui bahwa konten apapun yang berasal dari Platform dan digunakan untuk kepentingan Pengguna akan menjadi risiko mereka sendiri.</p>
                            <p>blitznet berhak, atas kebijakannya sendiri dan tanpa kewajiban apa pun, untuk melakukan perbaikan, atau memperbaiki kesalahan atau kelalaian di bagian mana pun dari Layanan yang ada di Platform.</p>
                           <p>blitznet bukan pakar dari perlindungan hak kekayaan intelektual pengguna, karenanya blitznet tidak dapat memverifikasi bahwa Pengguna Platform memiliki hak untuk menjual barang yang ditawarkan. blitznet menghargai laporan Pengguna dalam mengidentifikasi konten yang melanggar hak Pengguna sebagai pemilik asli konten. blitznet juga bukan merupakan arbiter atau hakim sengketa tentang hak kekayaan intelektual. Dengan menghapus daftar, sebagai hal yang hati-hati, blitznet tidak mendukung klaim pelanggaran. Dalam kasus di mana blitznet menolak untuk menghapus suatu nama Pengguna, blitznet tidak akan memutus bahwa Pengguna tersebut telah melanggar hak kekayaan intelektual Pengguna lain, dan blitznet juga tidak mendukung penjualan barang dalam kasus tersebut.</p>
                           <p>blitznet menghargai setiap hak kekayaan intelektual orang lain, dan blitznet berharap Pengguna melakukan hal yang sama. blitznet percaya bahwa pengguna setuju bahwa mereka tidak akan menyalin, mengunduh & mereproduksi informasi, teks, gambar, klip video, direktori, file, basis data, atau daftar apa pun yang tersedia di atau melalui situs web blitznet ("konten blitznet") untuk tujuan penjualan kembali atau pendistribusian ulang, pengiriman massal (melalui email, pesan teks nirkabel, surat fisik, atau lainnya), menjalankan bisnis yang bersaing dengan blitznet, atau dengan cara lain mengeksploitasi konten blitznet secara komersial. Pengambilan konten blitznet secara sistematis untuk membuat atau mengkompilasi, secara langsung atau tidak langsung, kumpulan, kompilasi, database atau direktori (baik melalui perangkat otomatis atau proses manual) tanpa izin tertulis dari blitznet adalah perbuatan yang dilarang.</p>
                            <p>Selain itu, penggunaan konten untuk tujuan apa pun yang tidak diizinkan secara tegas dalam Perjanjian ini dilarang dan dapat mengakibatkan keterlibatan hukum. Sebagai syarat akses Pengguna untuk menggunakan layanan blitznet, Pengguna harus setuju bahwa Pengguna tidak akan menggunakan Layanan blitznet untuk melanggar hak kekayaan intelektual orang lain dengan cara apa pun. blitznet berhak untuk menghentikan akun Pengguna atas pelanggaran hak orang lain sehubungan dengan penggunaan layanan blitznet, atau jika blitznet yakin bahwa tindakan Pengguna tersebut merugikan kepentingan blitznet, afiliasi, atau pengguna lain, atau untuk alasan lain atas kebijakan blitznet sendiri, dengan atau tanpa sebab.</p>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">PEMBATALAN</h5>
                            <p> Sebagian besar konten dan beberapa fitur Layanan blitznet tersedia untuk Pengguna secara gratis, berbayar, atau premium. Namun, blitznet berhak untuk menghentikan akses ke area atau fitur tertentu dari Layanan blitznet (untuk Pengguna yang membayar atau terdaftar) kapan saja dengan alasan apapun, dengan atau tanpa pemberitahuan. blitznet juga memiliki hak universal untuk menolak akses Pengguna tertentu ke setiap/semua layanan/kontennya tanpa pemberitahuan/penjelasan sebelumnya untuk melindungi kepentingan blitznet dan/atau Pengguna lain. blitznet berhak untuk membatasi, menolak atau membuat akses yang berbeda ke Layanan blitznet dan fitur-fiturnya sehubungan dengan Pengguna yang berbeda, atau untuk mengubah salah satu fitur atau memperkenalkan fitur baru tanpa pemberitahuan sebelumnya.</p>
                                <p>blitznet berhak untuk menangguhkan hak untuk penghentian sementara atau permanen keanggotaan setiap Pengguna karena salah satu alasan berikut:</p>

                            <ol class="list-group ms-3 my-4" type="a">
                                <li class="ms-5 mt-2">Jika terbukti bahwa Pengguna (pemilik akun) telah memberikan informasi palsu sehubungan dengan akun anggota ke blitznet, atau terlibat dalam kegiatan penipuan atau ilegal</li>
                                <li class="ms-5 mt-2">Pengguna melanggar ketentuan apa pun dari syarat dan ketentuan perjanjian penggunaan dan/atau Perjanjian Layanan blitznet</li>
                                <li class="ms-5 mt-2">Memanfaatkan Layanan blitznet untuk mengirim pesan spam atau mempublikasikan informasi produk yang sama berulang kali.</li>
                                <li class="ms-5 mt-2">Memposting materi apapun kepada Pengguna lain yang tidak terkait dengan perdagangan atau kerjasama bisnis.</li>
                                <li class="ms-5 mt-2">Meniru atau secara tidak sah menggunakan nama perusahaan lain untuk memposting informasi atau menjalankan bisnis dalam bentuk apa pun
                                </li>
                                <li class="ms-5 mt-2">Menyalahgunakan akses, penggunaan, modifikasi, atau kontrol yang tidak sah atas basis data, jaringan, atau layanan terkait Layanan blitznet.</li>
                            </ol>
                            <p>Jika blitznet mengakhiri keanggotaan Pengguna, maka Pengguna tidak akan memiliki hak untuk mendaftar ulang atau bergabung dengan blitznet dengan akun atau nama baru kecuali diundang secara resmi oleh blitznet. Dalam setiap kasus penghentian, tidak ada biaya keanggotaan yang akan dikembalikan. Pengguna mengakui bahwa ketidakmampuan untuk menggunakan Layanan blitznet secara keseluruhan atau sebagian karena alasan apapun dapat berdampak buruk pada bisnisnya. Pengguna dengan ini setuju bahwa blitznet tidak akan bertanggung jawab kepada Pengguna atau pihak ketiga mana pun atas ketidakmampuan Pengguna untuk menggunakan Layanan blitznet (baik karena gangguan, akses terbatas, perubahan atau penghentian fitur apa pun pada Layanan blitznet atau lainnya), keterlambatan, kesalahan, atau kelalaian apapun sehubungan dengan komunikasi atau transmisi apa pun, atau kerusakan apa pun (langsung, tidak langsung, konsekuensial, atau lainnya) yang timbul dari penggunaan atau ketidakmampuan untuk menggunakan Layanan blitznet atau salah satu fiturnya
                            </p>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">PENGGUNA TERDAFTAR</h5>
                            <p>Untuk menjadi Pengguna terdaftar, terdapat prosedur yang harus dilakukan untuk menjaga kenyaman calon Pengguna untuk mendaftarkan diri sebagai Pengguna layanan bliztnet</p>
                            <p>Pengguna dapat menjadi Pengguna Terdaftar dengan mengisi formulir pendaftaran online di Platform dengan memberikan informasi yang diinginkan (nama, informasi kontak, detail bisnisnya, dll.). blitznet akan membuat akun ("Akun") untuk pengguna saat pendaftaran dan menetapkan alias pengguna ("ID Pengguna") dan kata sandi ("Kata Sandi") untuk akses masuk ke Akun Anda.
                            </p>
                            <p>Jika Pengguna mendaftar atas nama entitas bisnis, Pengguna mewakili entitas bisnis tersebut dan (a) Pengguna memiliki wewenang untuk mengikat entitas tersebut dengan syarat dan ketentuan penggunaan dan/atau Perjanjian ini; (b) alamat yang Pengguna gunakan saat mendaftar adalah tempat usaha utama dari badan usaha tersebut; dan (c) semua informasi lain yang disampaikan ke blitznet selama proses pendaftaran adalah benar, akurat, terkini dan lengkap. Untuk keperluan ketentuan ini, cabang atau kantor perwakilan tidak akan dianggap sebagai entitas yang terpisah dan tempat usaha utama akan dianggap sebagai kantor pusatnya.
                            </p>
                            <p>Dengan menjadi Pengguna Terdaftar, Anda menyetujui penyertaan data pribadi Anda dalam basis data online kami dan mengizinkan blitznet untuk membagikan informasi tersebut kepada pengguna lain. blitznet dapat menolak pendaftaran dan menolak keanggotaan dan ID Pengguna dan Kata Sandi yang terkait kepada pengguna manapun dengan alasan apapun. Layanan blitznet dapat menangguhkan atau mengakhiri keanggotaan terdaftar setiap saat tanpa pemberitahuan sebelumnya untuk kepentingan blitznet atau kepentingan umum pengunjung/anggota lain tanpa memberikan alasan apapun. Pengguna Terdaftar bukan merupakan bagian atau afiliasi dari blitznet dengan cara apapun.
                            </p>
                            <p>Dengan ini, Saya setuju untuk dihubungi oleh PT Blitznet Upaya Indonesia ("blitznet") melalui panggilan telepon, notifikasi SMS atau sarana komunikasi lainnya, sehubungan dengan layanan yang diberikan oleh blitznet.</p>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">PERLINDUNGAN DATA</h5>
                            <p>Informasi pribadi yang diberikan oleh Pengguna selama penggunaan Layanan blitznet diatur oleh kebijakan privasi kami.</p>
                        </li>


                        <li class="ms-4 my-3">
                            <h5 class=" my-3">POSTING KONTEN ANDA PADA SITUS Blitznet DAN APLIKASI SELULER (IPR).                            </h5>
                            <p>Beberapa konten yang ditampilkan di situs web blitznet disediakan atau diposting oleh pihak ketiga. Pengguna dapat memposting konten mereka di beberapa bagian/layanan Layanan blitznet menggunakan alat bantu kirim dan edit secara mandiri yang disediakan di bagian terkait. Pengguna mungkin perlu mendaftar dan/atau membayar beberapa layanan ini.</p>
                            <p>blitznet dalam kasus tersebut bukan penulis. Konten di sini disumbangkan oleh pengguna anonim, terdaftar, atau berbayar. Baik blitznet maupun afiliasi, direktur, pejabat, atau karyawannya tidak pernah menjalin hubungan keagenan penjualan dengan pihak ketiga tersebut berdasarkan tampilan di Platform atas Konten Pihak Ketiga di situs web blitznet. Setiap konten Pihak Ketiga adalah tanggung jawab penuh dari pihak yang telah menyediakan konten tersebut. blitznet tidak bertanggung jawab atas keakuratan, kepatutan, keabsahan, atau kebenaran konten Pihak Ketiga mana pun, dan tidak akan bertanggung jawab kepada pengguna mana pun sehubungan dengan ketergantungannya pada konten Pihak Ketiga tersebut. Selain itu, blitznet tidak bertanggung jawab atas pelaksanaan aktivitas pengguna di situs web blitznet, dan tidak bertanggung jawab kepada siapa pun sehubungan dengan kerugian yang diderita oleh siapapun sebagai akibat dari tindakan pengguna tersebut.
                            </p>

                            <p class="mb-3">Pengguna semata-mata mewakili, menjamin, dan setuju untuk:</p>
                            <ol class="list-group ms-3 my-3" type="a">
                                <li class="ms-5">Memberikan blitznet informasi yang benar, akurat, terkini dan lengkap untuk ditampilkan di Platform; dan</li>
                                <li class="ms-5">memelihara dan segera mengubah semua informasi agar tetap benar, akurat, terkini, dan lengkap.</li>
                            </ol>

                            <p>Pengguna dengan ini memberikan lisensi yang tidak dapat dibatalkan, abadi, mendunia dan bebas royalti, dapat disublisensikan (melalui beberapa tingkatan) kepada blitznet untuk menampilkan dan menggunakan semua informasi yang diberikan oleh mereka sesuai dengan tujuan yang ditetapkan dalam perjanjian dan untuk menggunakan hak cipta, publisitas, dan hak basis data yang Pengguna miliki dalam materi atau informasi tersebut, dalam bentuk media apapun, hak cipta pihak ketiga, merek dagang, hak rahasia dagang, paten, dan hak pribadi atau hak milik lainnya yang memengaruhi atau terkait dengan materi atau informasi yang ditampilkan di situs web blitznet, termasuk namun tidak terbatas pada hak pribadi dan hak privasi, atau memengaruhi atau berkaitan dengan produk yang ditawarkan atau ditampilkan di Situs web blitznet (selanjutnya disebut "Hak Pihak Ketiga").</p>
                            <p>Pengguna dengan ini menyatakan, menjamin dan setuju bahwa pengguna bertanggung jawab penuh untuk memastikan bahwa setiap materi atau informasi yang Anda posting di Situs web blitznet atau memberikan kepada blitznet atau mengizinkan blitznet untuk ditampilkan, tidak, dan bahwa produk yang diwakili dengan demikian tidak, melanggar Hak Pihak Ketiga, atau diposting dengan izin dari pemilik hak tersebut. Pengguna dengan ini menyatakan, menjamin dan setuju bahwa mereka memiliki hak untuk memproduksi, menawarkan, menjual, mengimpor dan mendistribusikan produk yang ditawarkan dan ditampilkan pada Layanan blitznet, dan bahwa pembuatan, penawaran, penjualan, impor dan/atau distribusi tersebut produk tersebut tidak melanggar Hak Pihak Ketiga.</p>
                            <p>Pengguna dengan ini menyatakan, menjamin, dan menyetujui bahwa informasi yang dikirimkan ke blitznet untuk ditampilkan di situs web blitznet tidak akan:</p>
                            <ol class="list-group ms-3 my-3" type="a">
                                <li class="ms-5">Berisi informasi penipuan atau membuat penawaran barang palsu atau melibatkan penjualan atau percobaan penjualan barang palsu atau curian atau barang yang penjualan dan/atau pemasarannya dilarang oleh hukum yang berlaku, atau mempromosikan kegiatan ilegal lainnya;</li>
                                <li class="ms-5">Menjadi bagian dari skema untuk menipu Pengguna lain dari situs web blitznet atau untuk tujuan lain yang melanggar hukum;</li>
                                <li class="ms-5">Berkaitan dengan penjualan produk atau layanan yang melanggar atau bersekongkol atau mendorong pelanggaran atau pelanggaran hak cipta, paten, merek dagang, rahasia dagang pihak ketiga atau hak kepemilikan lainnya atau hak publisitas atau privasi, atau Hak Pihak Ketiga lainnya; </li>
                                <li class="ms-5">Melanggar hukum, undang-undang, ordonansi atau peraturan yang berlaku (termasuk namun tidak terbatas pada yang mengatur kontrol ekspor, perlindungan konsumen, persaingan tidak sehat, anti-diskriminasi atau iklan palsu);</li>
                                <li class="ms-5">Bersifat memfitnah, mengancam secara tidak sah, atau melecehkan secara tidak sah;</li>
                                <li class="ms-5">Bersikap cabul atau mengandung atau menyimpulkan pornografi atau barang dagangan yang berhubungan dengan seks atau konten lainnya atau mempromosikan materi seksual eksplisit atau berbahaya bagi anak di bawah umur;</li>
                                <li class="ms-5">Mendukung diskriminasi yang didasarkan pada ras, jenis kelamin, agama, kewarganegaraan, disabilitas, orientasi seksual dan umur;</li>
                                <li class="ms-5">Meminta bisnis dari Pengguna mana pun sehubungan dengan aktivitas komersial yang bersaing dengan blitznet;</li>
                                <li class="ms-5">Berisi materi apa pun yang merupakan iklan atau pelecehan yang tidak sah (termasuk tetapi tidak terbatas pada spamming), menyerang privasi siapa pun, atau mendorong perilaku yang merupakan pelanggaran pidana, menimbulkan tanggung jawab perdata, atau melanggar hukum atau peraturan apa pun; </li>
                                <li class="ms-5">Mengandung virus komputer atau perangkat dan kode perusak lainnya yang memiliki efek merusak, mengganggu, mencegat, atau mengambil alih sistem perangkat lunak atau perangkat keras, data, atau informasi pribadi apa pun;</li>
                                <li class="ms-5">Menautkan secara langsung atau tidak langsung ke atau menyertakan deskripsi barang atau jasa yang dilarang berdasarkan hukum yang berlaku; atau
                                </li>
                            </ol>
                            <p>Jika tidak, blitznet dan afiliasinya tidak akan bertanggung jawab terhadap akibat hukum yang akan terjadi kepada Pengguna. </p>
                            <p>blitznet berhak atas kebijakannya sendiri untuk menghapus materi/konten/foto/penawaran yang ditampilkan pada Layanan blitznet yang diyakini secara wajar melanggar hukum, dapat membuat blitznet bertanggung jawab, melanggar syarat dan ketentuan dan/atau Perjanjian atau dinyatakan tidak pantas menurut blitznet. blitznet berhak untuk bekerja sama sepenuhnya dengan otoritas pemerintah, penyelidik swasta, dan/atau pihak ketiga yang dirugikan dalam penyelidikan dugaan pelanggaran pidana atau perdata.
                            </p>
                            <p>Sehubungan dengan hal-hal tersebut di atas, blitznet dapat menangguhkan atau menghentikan Akun Pengguna manapun yang dianggap tepat oleh Situs web blitznet atas kebijakannya sendiri. Pengguna setuju bahwa Layanan blitznet tidak bertanggung jawab kepada Pengguna manapun, termasuk tidak bertanggung jawab atas konsekuensial atau kerugian lainnya, jika blitznet mengambil tindakan yang disebutkan dalam Bagian ini, dan bahwa Anda setuju untuk menanggung risiko blitznet dapat mengambil tindakan seperti itu.</p>
                            <p>blitznet bertindak sebagai integrator konten dan tidak bertanggung jawab atas informasi yang diberikan oleh pengguna untuk ditampilkan di Situs web blitznet. blitznet tidak memiliki peran dalam mengembangkan konten.</p>
                        </li>


                        <li class="ms-4 my-3">
                            <h5 class=" my-3">INTERAKSI ANTARA PENGGUNA</h5>
                            <p>blitznet menyediakan platform untuk bertukar informasi antara pembeli dan pemasok produk dan layanan. Layanan blitznet tidak mewakili penjual atau pembeli dalam setiap transaksi. blitznet tidak mengontrol dan tidak berkewajiban atau bertanggung jawab atas kualitas, keamanan, keabsahan atau ketersediaan produk atau layanan yang ditawarkan untuk dijual oleh blitznet atau kemampuan pemasok untuk menyelesaikan penjualan atau kemampuan pembeli untuk menyelesaikan pembelian. Pengguna diperingatkan bahwa mungkin ada risiko berurusan dengan warga negara asing atau orang yang bertindak dengan alasan palsu. blitznet tidak dapat dan tidak mengkonfirmasi setiap identitas pengguna.
                            </p>
                            <p>Pengguna mengakui bahwa pengguna sepenuhnya menanggung risiko transaksi pembelian dan penjualan saat menggunakan Layanan blitznet untuk melakukan transaksi, dan bahwa pengguna sepenuhnya menanggung risiko kewajiban atau kerugian dalam bentuk apa pun sehubungan dengan aktivitas selanjutnya dalam bentuk apa pun yang berkaitan dengan produk atau layanan yang menjadi subjek transaksi menggunakan Layanan blitznet.</p>
                            <p>Risiko tersebut termasuk, namun tidak terbatas pada, representasi produk dan layanan yang salah, skema penipuan, kualitas yang tidak memuaskan, kegagalan untuk memenuhi spesifikasi, produk yang cacat atau berbahaya, produk yang melanggar hukum, keterlambatan atau gagal bayar dalam pengiriman atau pembayaran, salah perhitungan biaya. pelanggaran garansi, pelanggaran kontrak dan kecelakaan transportasi. Risiko tersebut juga mencakup risiko bahwa pembuatan, impor, distribusi, penawaran, tampilan, pembelian, penjualan dan/atau penggunaan produk atau layanan yang ditawarkan dapat melanggar atau dapat dinyatakan melanggar Hak Pihak Ketiga, dan risiko bahwa Anda dapat dikenakan biaya pembelaan atau biaya lain sehubungan dengan penegasan pihak ketiga atas Hak Pihak Ketiga, atau sehubungan dengan klaim oleh pihak manapun bahwa mereka berhak atas pembelaan atau ganti rugi sehubungan dengan penegasan hak, tuntutan atau klaim oleh penggugat Hak Pihak Ketiga. Risiko tersebut juga termasuk risiko bahwa konsumen, pembeli lain, pengguna akhir produk atau pihak lain yang mengaku menderita cedera atau kerugian terkait dengan produk yang awalnya diperoleh oleh pengguna Layanan blitznet sebagai akibat dari transaksi pembelian dan penjualan sehubungan dengan menggunakan Layanan blitznet dapat menderita kerugian dan/atau mengajukan klaim yang timbul dari penggunaan produk tersebut oleh mereka. Semua risiko di atas selanjutnya disebut sebagai "Risiko Transaksi".
                            </p>
                            <p>Pengguna setuju bahwa blitznet tidak bertanggung jawab atau bertanggung jawab atas segala kerusakan, kewajiban, biaya, kerugian, ketidaknyamanan, gangguan bisnis atau pengeluaran dalam bentuk apa pun yang mungkin terjadi/timbul sebagai akibat dari atau sehubungan dengan Risiko Transaksi apa pun. Pengguna bertanggung jawab penuh atas semua syarat dan ketentuan transaksi yang dilakukan pada, melalui atau sebagai akibat dari penggunaan Layanan blitznet. Jika terjadi perselisihan dengan pihak manapun dalam suatu transaksi, pengguna setuju untuk membebaskan dan mengganti kerugian blitznet (dan agen, afiliasi, direktur, pejabat, dan karyawan kami) dari semua klaim, tuntutan, tindakan, proses, biaya, pengeluaran, dan kerusakan (termasuk namun tidak terbatas pada setiap kerusakan aktual, khusus, insidental atau konsekuensial) yang timbul dari atau sehubungan dengan transaksi tersebut. Pengguna dapat menggunakan konten/fitur pada Layanan blitznet hanya untuk tujuan pribadi atau internal mereka. Pengguna setuju bahwa mereka tidak akan menggunakan basis data dan/atau layanan blitznet untuk mengirim surat sampah, surat berantai, atau spam atau transmisi materi yang melanggar hukum, melecehkan, memfitnah, kasar, mengancam, berbahaya, vulgar, cabul, atau tidak pantas dari jenis atau sifat apapun. Selanjutnya, sebagai Pengguna Terdaftar, pengguna tidak akan menggunakan Akun Email untuk mempublikasikan, mendistribusikan, mengirimkan atau mengedarkan iklan atau informasi promosi yang tidak diminta atau konten apa pun yang cabul, tidak senonoh, menghasut, menyinggung, memfitnah, mengancam, atau yang menghasut atau mengakibatkan kebencian rasial, diskriminasi, ancaman, atau pelanggaran kepercayaan.</p>
                            <p>blitznet berhak untuk menambah/memodifikasi/menghentikan salah satu fitur yang ditawarkan dengan layanan.</p>
                        </li>

                        <li class="ms-4 my-3">
                            <h5 class=" my-3">FORCE MAJEURE</h5>
                            <p>Fitur Layanan blitznet disediakan atas dasar "sebagaimana adanya" dan "sebagaimana tersedia", dan blitznet dengan ini secara tegas menolak setiap dan semua jaminan, tersurat maupun tersirat, termasuk namun tidak terbatas pada jaminan kondisi, kualitas, daya tahan, kinerja, akurasi, keandalan, kelayakan untuk diperdagangkan, atau kesesuaian untuk tujuan tertentu. Semua jaminan, pernyataan, kondisi, usaha, dan persyaratan tersebut dengan ini dikecualikan. blitznet tidak membuat pernyataan atau jaminan tentang validitas, keakuratan, kebenaran, keandalan, kualitas, stabilitas, dan kelengkapan informasi apa pun yang disediakan pada atau melalui Layanan blitznet. blitznet tidak menyatakan atau menjamin bahwa pembuatan, impor, distribusi, penawaran, tampilan, pembelian, penjualan dan/atau penggunaan produk atau layanan yang ditawarkan atau ditampilkan pada Layanan blitznet tidak melanggar hak pihak ketiga mana pun; dan blitznet tidak membuat pernyataan atau jaminan dalam bentuk apa pun mengenai produk atau layanan apa pun yang ditawarkan atau ditampilkan di Layanan blitznet. Materi apa pun yang diunduh atau diperoleh melalui Layanan blitznet dilakukan atas kebijakan dan risiko Anda sendiri dan Anda bertanggung jawab penuh atas segala kerusakan pada sistem komputer Anda atau hilangnya data yang mungkin diakibatkan oleh pengunduhan materi tersebut. Tidak ada saran atau informasi, baik lisan maupun tertulis, yang Anda peroleh dari Layanan blitznet atau melalui atau dari Layanan blitznet yang akan menimbulkan jaminan apapun yang tidak dinyatakan secara tegas di sini.
                            </p>
                            <p>Dalam keadaan apapun Layanan blitznet tidak bertanggung jawab atas keterlambatan atau kegagalan atau gangguan konten atau layanan yang disampaikan melalui Layanan blitznet yang diakibatkan secara langsung atau tidak langsung dari tindakan alam, kekuatan, atau penyebab di luar kendali yang wajar, termasuk namun tidak terbatas pada, kegagalan Internet, komputer, telekomunikasi atau kegagalan peralatan lainnya, kegagalan daya listrik, pemogokan, perselisihan perburuhan, kerusuhan, pemberontakan, gangguan sipil, kekurangan tenaga kerja atau bahan, kebakaran, banjir, badai, ledakan, Kehendak Tuhan, bencana alam, perang, tindakan pemerintah, perintah pengadilan atau tribunal domestik atau asing atau non-kinerja pihak ketiga. Pengguna dengan ini setuju untuk mengganti kerugian dan menyelamatkan blitznet, afiliasinya, direktur, pejabat dan karyawannya dari setiap dan semua kerugian, klaim, kewajiban (termasuk biaya hukum atas dasar ganti rugi penuh) yang mungkin timbul dari penggunaan blitznet oleh Anda Layanan (termasuk namun tidak terbatas pada tampilan informasi Anda di Situs web blitznet) atau dari pelanggaran Anda terhadap salah satu syarat dan ketentuan Perjanjian ini. Pengguna dengan ini selanjutnya setuju untuk mengganti kerugian dan menyelamatkan blitznet, afiliasinya, direktur, pejabat dan karyawannya, dari setiap dan semua kerugian, klaim, kewajiban (termasuk biaya hukum atas dasar ganti rugi penuh) yang mungkin timbul dari pelanggaran Anda terhadap setiap pernyataan dan jaminan yang Anda buat untuk blitznet.
                            </p>
                            <p>Pengguna dengan ini selanjutnya setuju untuk mengganti kerugian dan menyelamatkan blitznet, afiliasinya, direktur, pejabat dan karyawannya, dari setiap dan semua kerugian, klaim, kewajiban (termasuk biaya hukum dengan ganti rugi penuh) yang mungkin timbul, secara langsung atau tidak langsung, sebagai akibat dari klaim apapun yang diajukan oleh penggugat Hak Pihak Ketiga atau pihak ketiga lainnya terkait dengan produk yang ditawarkan atau ditampilkan di Situs web blitznet sebaliknya. Pengguna dengan ini selanjutnya setuju bahwa blitznet tidak bertanggung jawab dan tidak memiliki kewajiban untuk itu, untuk setiap materi yang diposting oleh orang lain; termasuk materi yang memfitnah, menyinggung, atau terlarang dan bahwa risiko kerusakan dari materi tersebut sepenuhnya ada pada Anda. blitznet berhak, dengan biayanya sendiri, untuk menanggung pembelaan dan kendali eksklusif atas masalah apa pun yang tunduk pada ganti rugi oleh Anda, di mana Anda harus bekerja sama dengan blitznet dalam menegaskan pembelaan apapun yang tersedia.</p>
                            <p>blitznet tidak bertanggung jawab atas kerusakan khusus, langsung, tidak langsung, akibat hukum, insidental atau konsekuensial atau kerusakan apapun (termasuk tetapi tidak terbatas pada kerusakan karena kehilangan keuntungan atau tabungan, gangguan bisnis, kehilangan informasi), baik dalam kontrak, kelalaian, kesalahan, tanggung jawab ketat atau sebaliknya atau kerusakan lainnya.</p>

                            </li>

                            <li class="ms-4 my-3">
                                <h5 class=" my-3">PEMBERITAHUAN</h5>
                                <p>Semua pemberitahuan atau tuntutan kepada atau atas blitznet akan berlaku efektif jika dibuat secara tertulis dan harus dibuat sebagaimana mestinya pada saat dikirim ke blitznet dengan cara sebagai berikut: kepada PT Blitznet Upaya Indonesia. Alamanda Tower Lantai 25. Jl TB Simatupang Kav 23-24, Cilandak Barat, Cilandak, Jakarta Selatan. DKI Jakarta.</p>
                                <p>Semua pemberitahuan atau permintaan kepada atau atas Pengguna akan berlaku jika disampaikan secara pribadi, dikirim melalui kurir, surat resmi, melalui faksimili atau email ke korespondensi, faks, atau alamat email yang terakhir diketahui yang diberikan oleh Pengguna kepada blitznet, atau dengan memasang pemberitahuan atau permintaan tersebut di area Situs web blitznet.</p>
                                <p>Pemberitahuan kepada Pengguna akan dianggap telah diterima oleh Pengguna tersebut jika dan ketika blitznet dapat menunjukkan bahwa komunikasi, baik dalam bentuk fisik atau elektronik, telah dikirimkan kepada Pengguna tersebut, atau segera setelah blitznet memposting pemberitahuan tersebut di area situs web blitznet.</p>
                                </li>


                        <li class="ms-4 my-3">
                            <h5 class=" my-3">HUKUM YANG BERLAKU DAN LEMBAGA PENYELESAIAN MASALAH</h5>
                            <p>Syarat dan Ketentuan yang digunakan di Perjanjian ini, dan dokumen yang berkaitan dengan kebijakan lainnya patuh pada hukum Negara Kesatuan Republik Indonesia. Seluruh penyelesaian masalah yang timbul di kemudian hari dan melibatkan blitznet di dalamnya akan diselesaikan di Pengadilan Negeri Jakarta Selatan. 
                            </p>

                        </li>
                        <li class="ms-4 my-3">
                            <h5 class=" my-3">PASAL TAMBAHAN</h5>
                            <p>Judul adalah untuk tujuan referensi saja dan sama sekali tidak mendefinisikan, membatasi, menafsirkan atau menggambarkan ruang lingkup atau luas bagian tersebut.</p>
                            <p>Kegagalan blitznet untuk menegakkan hak atau kegagalan untuk bertindak sehubungan dengan pelanggaran apapun oleh Pengguna berdasarkan syarat dan ketentuan ini tidak akan melepaskan hak itu atau mengesampingkan hak blitznet untuk bertindak sehubungan dengan pelanggaran berikutnya atau serupa.</p>
                            <p>blitznet berhak untuk mengalihkan kewajiban dan tugasnya dalam Perjanjian ini dan dalam setiap perjanjian yang berkaitan dengan setiap/semua Layanannya kepada orang atau entitas mana pun.</p>
                            <p>Jika ada ketentuan dari syarat dan ketentuan penggunaan dan/atau Perjanjian yang dianggap tidak sah atau tidak dapat dilaksanakan, ketentuan tersebut akan dibatalkan dan ketentuan lainnya akan diberlakukan.</p>
                            <p>Semua komunikasi yang terjadi di Platform sepenuhnya rahasia. Namun, komunikasi yang dilakukan oleh Pelanggan mungkin direkam untuk memastikan kualitas layanan. Selanjutnya, untuk tujuan pelatihan dan untuk memastikan layanan pelanggan yang sangat baik, panggilan dari blitznet dapat dipantau dan direkam.</p>
                            <p>Syarat dan ketentuan penggunaan dan/atau Perjanjian dan Kebijakan Privasi yang disebutkan di atas merupakan keseluruhan perjanjian antara Pengguna dan blitznet sehubungan dengan akses ke dan penggunaan Layanan blitznet, menggantikan perjanjian tertulis atau lisan sebelumnya terkait untuk materi pelajaran yang sama di sini.</p>
                        </li>
                    </ol>
                </div>
            </div>',
);
